// inertia/pages/auth/login.tsx
import { Button, Checkbox, Field, Input, Label } from '@headlessui/react'
import { Icon } from '@iconify/react'
import { Head, Link, useForm } from '@inertiajs/react'
import clsx from 'clsx'
import Show from '~/helpers/show'

function Login() {
  const form = useForm({
    email: '',
    password: '',
    remember: true,
  })

  function submit(e: React.FormEvent) {
    e.preventDefault()

    if (form.processing) return

    form.post('/login', {
      onFinish: () => {
        form.reset('password')
      },
    })
  }

  return (
    <>
      <Head title="Se connecter" />

      <div className="flex flex-col items-center">
        <h1 className="text-4xl font-medium text-slate-700">Se connecter</h1>
        <span className="text-slate-500">
          ou{' '}
          <Link href="/register" className="text-amber-500 hover:underline">
            créer un compte
          </Link>
        </span>
      </div>

      <form onSubmit={submit} className="flex w-full flex-col space-y-6" autoComplete="off">
        <Field className="flex flex-col">
          <Label className="text-slate-700">Adresse e-mail</Label>
          <Input
            required
            type="email"
            value={form.data.email}
            onChange={(e) => form.setData('email', e.target.value)}
            className={clsx(
              'rounded border p-4 text-slate-500 transition data-[focus]:outline-none',
              form.errors.email
                ? 'border-red-300 bg-red-50 data-[focus]:border-red-300'
                : 'border-slate-300 bg-slate-100 data-[focus]:border-amber-300 data-[focus]:bg-amber-50'
            )}
          />
        </Field>

        <Field className="flex flex-col">
          <div className="flex items-center justify-between">
            <Label className="text-slate-700">Mot de passe</Label>
            <Link href="/forgot-password" className="text-sm text-slate-500 hover:text-amber-500">
              Mot de passe oublié ?
            </Link>
          </div>
          <Input
            required
            type="password"
            value={form.data.password}
            onChange={(e) => form.setData('password', e.target.value)}
            className={clsx(
              'rounded border p-4 text-slate-500 transition data-[focus]:outline-none',
              form.errors.password
                ? 'border-red-300 bg-red-50 data-[focus]:border-red-300'
                : 'border-slate-300 bg-slate-100 data-[focus]:border-amber-300 data-[focus]:bg-amber-50'
            )}
          />
        </Field>

        <Field className="flex items-center gap-2">
          <Checkbox
            checked={form.data.remember}
            onChange={(checked) => form.setData('remember', checked)}
            className="group block rounded border border-slate-300 bg-slate-100"
          >
            <Icon
              icon="heroicons:check-16-solid"
              className="size-4 text-slate-700 opacity-0 group-data-[checked]:opacity-100"
            />
          </Checkbox>
          <Label className="text-sm text-slate-500">Se souvenir de moi</Label>
        </Field>

        <Button
          type="submit"
          disabled={form.processing}
          className="flex justify-center rounded bg-slate-700 p-4 text-lg/6 text-white transition data-[disabled]:cursor-not-allowed data-[hover]:opacity-90"
        >
          <Show when={form.processing} fallback="Se connecter">
            <div className="size-6">
              <Icon icon="gg:spinner-two" className="size-6 animate-spin" />
            </div>
          </Show>
        </Button>

        <div className="flex items-center gap-5">
          <div className="w-full border-b border-slate-200"></div>
          <span className="font-semibold text-slate-500">ou</span>
          <div className="w-full border-b border-slate-200"></div>
        </div>

        <a
          href="/discord/redirect"
          className="flex items-center justify-center gap-4 rounded bg-[#7289da] p-2.5 text-white transition hover:opacity-90"
        >
          <div className="rounded-full bg-white p-2 transition hover:scale-105">
            <Icon icon="simple-icons:discord" className="size-6 text-[#7289da]" />
          </div>
          <span>Se connecter avec Discord</span>
        </a>
      </form>
    </>
  )
}

export default Login

// inertia/pages/auth/login.vue
<script setup lang="ts">
import { Icon } from '@iconify/vue'
import { Head, Link, useForm } from '@inertiajs/vue3'

const form = useForm({
  email: null,
  password: null,
  remember: true,
})

function submit() {
  if (form.processing) return

  form.post('/login', {
    onFinish: () => {
      form.reset('password')
    },
  })
}

function test() {
  form.reset()
}
</script>

<template>
  <Head title="Se connecter" />

  <div class="flex flex-col items-center">
    <button @click="test">reset</button>
    <h1 class="text-4xl font-medium text-slate-700">Se connecter</h1>
    <span class="text-slate-500">
      ou
      <Link href="/register" class="text-amber-500 hover:underline"> créer un compte </Link>
    </span>
  </div>

  <form @submit.prevent="submit" class="flex w-full flex-col space-y-6" autocomplete="off">
    <div class="flex flex-col">
      <label class="text-slate-700">Adresse e-mail</label>
      <input
        required
        type="email"
        v-model="form.email"
        class="rounded border p-4 text-slate-500 transition focus:outline-none"
        :class="
          form.errors.email
            ? 'border-red-300 bg-red-50 focus:border-red-300'
            : 'border-slate-300 bg-slate-100 focus:border-amber-300 focus:bg-amber-50'
        "
      />
    </div>

    <div class="flex flex-col">
      <div class="flex items-center justify-between">
        <label class="text-slate-700">Mot de passe</label>
        <Link href="/forgot-password" class="text-sm text-slate-500 hover:text-amber-500">
          Mot de passe oublié ?
        </Link>
      </div>
      <input
        required
        type="password"
        v-model="form.password"
        class="rounded border p-4 text-slate-500 transition focus:outline-none"
        :class="
          form.errors.password
            ? 'border-red-300 bg-red-50 focus:border-red-300'
            : 'border-slate-300 bg-slate-100 focus:border-amber-300 focus:bg-amber-50'
        "
      />
    </div>

    <div class="flex items-center gap-2">
      <input type="checkbox" v-model="form.remember" />
      <label class="text-sm text-slate-500">Se souvenir de moi</label>
    </div>

    <button
      type="submit"
      :disabled="form.processing"
      class="flex justify-center rounded bg-slate-700 p-4 text-lg/6 text-white transition hover:opacity-90 disabled:cursor-not-allowed"
    >
      <div v-if="form.processing" class="size-6">
        <Icon icon="gg:spinner-two" class="size-6 animate-spin" />
      </div>
      <span v-else>Se connecter</span>
    </button>

    <div class="flex items-center gap-5">
      <div class="w-full border-b border-slate-200"></div>
      <span class="font-semibold text-slate-500">ou</span>
      <div class="w-full border-b border-slate-200"></div>
    </div>

    <a
      href="/discord/redirect"
      class="flex items-center justify-center gap-4 rounded bg-[#7289da] p-2.5 text-white transition hover:opacity-90"
    >
      <div class="rounded-full bg-white p-2 transition hover:scale-105">
        <Icon icon="simple-icons:discord" class="size-6 text-[#7289da]" />
      </div>
      <span>Se connecter avec Discord</span>
    </a>
  </form>
</template>
