// inertia/pages/auth/register.tsx
import { Head, Link, useForm } from '@inertiajs/react'
import { Button, Field, Input, Label } from '@headlessui/react'
import clsx from 'clsx'
import { Icon } from '@iconify/react/dist/iconify.js'

function Register() {
  const form = useForm({
    username: '',
    email: '',
    password: '',
  })

  function submit(e: React.FormEvent) {
    e.preventDefault()

    if (form.processing) return

    form.post('/register', {
      onFinish: () => {
        form.reset('password')
      },
    })
  }

  return (
    <>
      <Head title="Créer un compte" />

      <div className="flex flex-col items-center">
        <h1 className="text-4xl font-medium text-slate-700">Créer un compte</h1>
        <span className="text-slate-500">
          ou{' '}
          <Link href="/login" className="text-amber-500 hover:underline">
            se connecter
          </Link>
        </span>
      </div>

      <form onSubmit={submit} className="flex w-full flex-col space-y-6">
        <Field className="flex flex-col">
          <Label className="text-slate-700">Nom d'utilisateur</Label>
          <Input
            type="text"
            required
            value={form.data.username}
            onChange={(e) => form.setData('username', e.target.value)}
            className={clsx(
              'rounded border p-4 text-slate-500 transition data-[focus]:outline-none',
              form.errors.username
                ? 'border-red-300 bg-red-50 data-[focus]:border-red-300'
                : 'border-slate-300 bg-slate-100 data-[focus]:border-amber-300 data-[focus]:bg-amber-50'
            )}
          />
          {form.errors.username && (
            <span className="mt-1 flex items-center gap-2 text-sm text-red-500">
              {form.errors.username}
            </span>
          )}
        </Field>

        <Field className="flex flex-col">
          <Label className="text-slate-700">Adresse e-mail</Label>
          <Input
            type="email"
            required
            value={form.data.email}
            onChange={(e) => form.setData('email', e.target.value)}
            className={clsx(
              'rounded border p-4 text-slate-500 transition data-[focus]:outline-none',
              form.errors.email
                ? 'border-red-300 bg-red-50 data-[focus]:border-red-300'
                : 'border-slate-300 bg-slate-100 data-[focus]:border-amber-300 data-[focus]:bg-amber-50'
            )}
          />
          {form.errors.email && (
            <span className="mt-1 flex items-center gap-2 text-sm text-red-500">
              {form.errors.email}
            </span>
          )}
        </Field>

        <Field className="flex flex-col">
          <Label className="text-slate-700">Mot de passe</Label>
          <Input
            type="password"
            required
            value={form.data.password}
            onChange={(e) => form.setData('password', e.target.value)}
            className={clsx(
              'rounded border p-4 text-slate-500 transition data-[focus]:outline-none',
              form.errors.password
                ? 'border-red-300 bg-red-50 data-[focus]:border-red-300'
                : 'border-slate-300 bg-slate-100 data-[focus]:border-amber-300 data-[focus]:bg-amber-50'
            )}
          />
          {form.errors.password && (
            <span className="mt-1 flex items-center gap-2 text-sm text-red-500">
              {form.errors.password}
            </span>
          )}
        </Field>

        <Button
          type="submit"
          disabled={form.processing}
          className="flex justify-center rounded border border-amber-500 bg-gradient-to-r from-amber-500 to-amber-300 p-4 text-lg/6 text-white transition data-[disabled]:cursor-not-allowed data-[hover]:opacity-90"
        >
          {form.processing ? (
            <Icon icon="gg:spinner-two" className="size-6 animate-spin" />
          ) : (
            'Créer un compte'
          )}
        </Button>

        <div className="flex items-center gap-5">
          <div className="w-full border-b border-slate-200"></div>
          <span className="font-semibold text-slate-500">ou</span>
          <div className="w-full border-b border-slate-200"></div>
        </div>

        <a
          href="/discord/redirect"
          className="flex items-center justify-center gap-4 rounded bg-[#7289da] p-2.5 text-white transition hover:opacity-90"
        >
          <div className="rounded-full bg-white p-2 transition hover:scale-105">
            <Icon icon="simple-icons:discord" className="size-6 text-[#7289da]" />
          </div>
          <span>Se connecter avec Discord</span>
        </a>
      </form>
    </>
  )
}

export default Register

// inertia/pages/auth/register.vue
<script setup lang="ts">
import { Icon } from '@iconify/vue'
import { Head, Link, useForm } from '@inertiajs/vue3'

const form = useForm({
  username: null,
  email: null,
  password: null,
})

function submit() {
  if (form.processing) return

  form.post('/register', {
    onFinish: () => {
      form.reset('password')
    },
  })
}
</script>

<template>
  <Head title="Créer un compte" />

  <div class="flex flex-col items-center">
    <h1 class="text-4xl font-medium text-slate-700">Créer un compte</h1>
    <span class="text-slate-500">
      ou
      <Link href="/login" class="text-amber-500 hover:underline"> se connecter </Link>
    </span>
  </div>

  <form @submit.prevent="submit" class="flex w-full flex-col space-y-6" autocomplete="off">
    <div class="flex flex-col">
      <label class="text-slate-700">Nom d'utilisateur</label>
      <input
        required
        type="text"
        v-model="form.username"
        class="rounded border p-4 text-slate-500 transition focus:outline-none"
        :class="
          form.errors.username
            ? 'border-red-300 bg-red-50 focus:border-red-300'
            : 'border-slate-300 bg-slate-100 focus:border-amber-300 focus:bg-amber-50'
        "
      />
      <span v-if="form.errors.username" class="mt-1 flex items-center gap-2 text-sm text-red-500">
        {{ form.errors.username[0] }}
      </span>
    </div>

    <div class="flex flex-col">
      <label class="text-slate-700">Adresse e-mail</label>
      <input
        required
        type="email"
        v-model="form.email"
        class="rounded border p-4 text-slate-500 transition focus:outline-none"
        :class="
          form.errors.email
            ? 'border-red-300 bg-red-50 focus:border-red-300'
            : 'border-slate-300 bg-slate-100 focus:border-amber-300 focus:bg-amber-50'
        "
      />
      <span v-if="form.errors.email" class="mt-1 flex items-center gap-2 text-sm text-red-500">
        {{ form.errors.email[0] }}
      </span>
    </div>

    <div class="flex flex-col">
      <label class="text-slate-700">Mot de passe</label>
      <input
        required
        type="password"
        v-model="form.password"
        class="rounded border p-4 text-slate-500 transition focus:outline-none"
        :class="
          form.errors.password
            ? 'border-red-300 bg-red-50 focus:border-red-300'
            : 'border-slate-300 bg-slate-100 focus:border-amber-300 focus:bg-amber-50'
        "
      />
      <span v-if="form.errors.password" class="mt-1 flex items-center gap-2 text-sm text-red-500">
        {{ form.errors.password[0] }}
      </span>
    </div>

    <button
      type="submit"
      :disabled="form.processing"
      class="flex justify-center rounded bg-slate-700 p-4 text-lg/6 text-white transition hover:opacity-90 disabled:cursor-not-allowed"
    >
      <div v-if="form.processing" class="size-6">
        <Icon icon="gg:spinner-two" class="size-6 animate-spin" />
      </div>
      <span v-else>Créer un compte</span>
    </button>

    <div class="flex items-center gap-5">
      <div class="w-full border-b border-slate-200"></div>
      <span class="font-semibold text-slate-500">ou</span>
      <div class="w-full border-b border-slate-200"></div>
    </div>

    <a
      href="/discord/redirect"
      class="flex items-center justify-center gap-4 rounded bg-[#7289da] p-2.5 text-white transition hover:opacity-90"
    >
      <div class="rounded-full bg-white p-2 transition hover:scale-105">
        <Icon icon="simple-icons:discord" class="size-6 text-[#7289da]" />
      </div>
      <span>Se connecter avec Discord</span>
    </a>
  </form>
</template>
