// resources/js/pages/auth/ResetPassword.vue
<script setup>
import { useForm } from '@inertiajs/vue3'
import { ExclamationTriangleIcon } from '@heroicons/vue/20/solid'
import AuthLayout from '@/layouts/AuthLayout.vue'

const props = defineProps(['email', 'token'])

const form = useForm({
  password: '',
  password_confirmation: '',
})

function submit() {
  form
    .transform((data) => ({
      ...data,
      email: props.email,
      token: props.token,
    }))
    .post('/reset-password', {
      onError: () => {
        form.reset('password', 'password_confirmation')
        document.activeElement.blur()
      },
      replace: true,
    })
}
</script>

<template>
  <Head title="Modifier mon mot de passe" />

  <form @submit.prevent="submit" autocomplete="off" novalidate>
    <div class="mb-6">
      <label for="email" class="mb-3 flex items-center justify-between text-slate-300">
        <span class="font-medium">Adresse e-mail</span>
        <div v-if="form.errors.email" class="flex items-center gap-2 text-sm text-red-500">
          <ExclamationTriangleIcon class="h-5 w-5" />
          <span>{{ form.errors.email[0] }}</span>
        </div>
      </label>
      <input
        required
        readonly
        type="email"
        id="email"
        name="email"
        :value="email"
        class="w-full cursor-not-allowed rounded border border-slate-600 bg-slate-950 p-4 text-slate-500 opacity-60 shadow-lg transition focus:outline-none" />
    </div>

    <div class="mb-6">
      <label for="password" class="mb-3 flex items-center justify-between text-slate-300">
        <span class="font-medium">Mot de passe</span>
        <div v-if="form.errors.password" class="flex items-center gap-2 text-sm text-red-500">
          <ExclamationTriangleIcon class="h-5 w-5" />
          <span>{{ form.errors.password[0] }}</span>
        </div>
      </label>
      <input
        required
        type="password"
        id="password"
        name="password"
        v-model="form.password"
        class="w-full rounded border border-slate-600 bg-slate-950 p-4 text-slate-500 opacity-60 shadow-lg transition focus:opacity-100 focus:outline-none" />
    </div>

    <div class="mb-6">
      <label
        for="password_confirmation"
        class="mb-1 flex items-center justify-between text-slate-300">
        <span class="font-medium">Confirmation mot de passe</span>
        <div
          v-if="form.errors.password_confirmation"
          class="flex items-center gap-2 text-sm text-red-500">
          <ExclamationTriangleIcon class="h-6 w-6" />
          <span>{{ form.errors.password_confirmation[0] }}</span>
        </div>
      </label>
      <input
        required
        type="password"
        id="password_confirmation"
        name="password_confirmation"
        v-model="form.password_confirmation"
        class="w-full rounded border border-slate-600 bg-slate-950 p-4 text-slate-500 opacity-60 shadow-lg transition focus:opacity-100 focus:outline-none" />
    </div>

    <button
      :disabled="form.processing"
      type="submit"
      class="disabled:hover:none mt-12 w-full rounded border border-sky-700 bg-sky-950 p-4 text-sky-300 transition hover:bg-sky-700 hover:text-sky-200 disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:bg-sky-950">
      Modifier mon mot de passe
    </button>
  </form>
</template>

// inertia/pages/auth/reset_password.tsx
import { Button, Field, Input, Label } from '@headlessui/react'
import { Head, useForm } from '@inertiajs/react'
import clsx from 'clsx'
import Spinner from '~/components/spinner'

type Props = {
  email: string
  token: string
}

function ResetPassword({ email, token }: Props) {
  const form = useForm({
    password: '',
    passwordConfirmation: '',
  })

  function submit(e: React.FormEvent) {
    e.preventDefault()

    if (form.processing) return

    form.transform((data) => ({
      ...data,
      token,
    }))

    form.post('/reset-password', {
      onFinish() {
        form.reset()
      },
    })
  }

  return (
    <>
      <Head title="Modifier mot de passe" />

      <h1 className="mb-6 text-4xl font-medium text-slate-700">Modifier mot de passe</h1>

      <form onSubmit={submit} className="flex w-full flex-col space-y-6">
        <Field className="flex flex-col" disabled>
          <Label className="text-slate-700">Adresse e-mail</Label>
          <Input
            required
            readOnly
            type="email"
            value={email}
            className="rounded border p-4 text-slate-500 transition data-[disabled]:cursor-not-allowed data-[focus]:border-slate-100 data-[disabled]:bg-slate-50 data-[disabled]:text-slate-400 data-[focus]:outline-none"
          />
        </Field>

        <Field className="flex flex-col">
          <Label className="text-slate-700">Mot de passe</Label>
          <Input
            required
            type="password"
            value={form.data.password}
            onChange={(e) => form.setData('password', e.target.value)}
            className={clsx(
              'rounded border p-4 text-slate-500 transition data-[focus]:outline-none',
              form.errors.password
                ? 'border-red-300 bg-red-50 data-[focus]:border-red-300'
                : 'border-slate-300 bg-slate-100 data-[focus]:border-amber-300 data-[focus]:bg-amber-50'
            )}
          />
          {form.errors.password && (
            <span className="mt-1 flex items-center gap-2 text-sm text-red-500">
              {form.errors.password}
            </span>
          )}
        </Field>

        <Field className="flex flex-col">
          <Label className="text-slate-700">Confirmation mot de passe</Label>
          <Input
            required
            type="password"
            value={form.data.passwordConfirmation}
            onChange={(e) => form.setData('passwordConfirmation', e.target.value)}
            className={clsx(
              'rounded border p-4 text-slate-500 transition data-[focus]:outline-none',
              form.errors.password
                ? 'border-red-300 bg-red-50 data-[focus]:border-red-300'
                : 'border-slate-300 bg-slate-100 data-[focus]:border-amber-300 data-[focus]:bg-amber-50'
            )}
          />
        </Field>

        <Button
          type="submit"
          disabled={form.processing}
          className="flex justify-center rounded border border-amber-500 bg-gradient-to-r from-amber-500 to-amber-300 p-4 text-lg font-medium text-white transition data-[disabled]:cursor-not-allowed data-[hover]:opacity-90"
        >
          {form.processing ? <Spinner text="Modification" /> : 'Modifier mot de passe'}
        </Button>
      </form>
    </>
  )
}

export default ResetPassword
