// inertia/components/main_nav_item.tsx
import { Link, usePage } from '@inertiajs/react'
import clsx from 'clsx'
import { ReactNode } from 'react'

type Props = {
  href: string
  children: ReactNode
}

function MainNavItem({ href, children }: Props) {
  const { url } = usePage()

  return (
    <Link href={href} className={clsx('hover:text-amber-500', url === href && 'text-slate-700')}>
      {children}
    </Link>
  )
}

export default MainNavItem

// inertia/components/MainNavItem.vue
<script setup lang="ts">
import { SharedProps } from '@adonisjs/inertia/types'
import { Link, usePage } from '@inertiajs/vue3'
import { computed } from 'vue'

defineProps<{ href: string }>()

const page = usePage<SharedProps>()

const url = computed(() => page.url)
</script>

<template>
  <Link :href class="hover:text-amber-500" :class="{ 'text-slate-700': url === href }">
    <slot />
  </Link>
</template>
