// inertia/pages/auth/forgot_password.tsx
import { Button, Field, Input, Label } from '@headlessui/react'
import { Icon } from '@iconify/react'
import { Head, useForm } from '@inertiajs/react'
import clsx from 'clsx'

function ForgotPassword() {
  const form = useForm({
    email: '',
  })

  function submit(e: React.FormEvent) {
    e.preventDefault()

    if (form.processing) return

    form.post('/forgot-password', {
      onSuccess() {
        form.reset()
      },
    })
  }

  return (
    <>
      <Head title="Mot de passe oublié" />

      <h1 className="mb-6 text-4xl font-medium text-slate-700">Mot de passe oublié</h1>

      <form onSubmit={submit} className="flex w-full flex-col space-y-6" autoComplete="off">
        <Field className="flex flex-col">
          <Label className="text-slate-700">Adresse e-mail</Label>
          <Input
            type="email"
            required
            value={form.data.email}
            onChange={(e) => form.setData('email', e.target.value)}
            className={clsx(
              'rounded border p-4 text-slate-500 transition data-[focus]:outline-none',
              form.errors.email
                ? 'border-red-300 bg-red-50 data-[focus]:border-red-300'
                : 'border-slate-300 bg-slate-100 data-[focus]:border-amber-300 data-[focus]:bg-amber-50'
            )}
          />
          {form.errors.email && (
            <span className="mt-1 flex items-center gap-2 text-sm text-red-500">
              {form.errors.email}
            </span>
          )}
        </Field>

        <Button
          type="submit"
          disabled={form.processing}
          className="flex justify-center rounded bg-slate-700 p-4 text-lg/6 text-white transition data-[disabled]:cursor-not-allowed data-[hover]:opacity-90"
        >
          {form.processing ? (
            <div className="size-6">
              <Icon icon="gg:spinner-two" className="size-6 animate-spin" />
            </div>
          ) : (
            'Réinitialiser mot de passe'
          )}
        </Button>
      </form>
    </>
  )
}

export default ForgotPassword

// resources/js/pages/auth/ForgotPassword.vue
<script setup>
import { useForm } from '@inertiajs/vue3'
import { ExclamationTriangleIcon } from '@heroicons/vue/20/solid'
import AuthLayout from '@/layouts/AuthLayout.vue'

const form = useForm({
  email: '',
})

function submit() {
  form.post('/forgot-password', {
    onSuccess: () => {
      form.reset('email')
      document.activeElement.blur()
    },
    replace: true,
  })
}
</script>

<template>
  <Head title="Mot de passe oublié" />

  <form @submit.prevent="submit" autocomplete="off" novalidate>
    <div class="mb-6">
      <label for="email" class="mb-3 flex items-center justify-between text-slate-300">
        <span class="font-medium">Adresse e-mail</span>
        <div v-if="form.errors.email" class="flex items-center gap-2 text-sm text-red-500">
          <ExclamationTriangleIcon class="h-5 w-5" />
          <span>{{ form.errors.email[0] }}</span>
        </div>
      </label>
      <input
        required
        type="email"
        id="email"
        name="email"
        v-model="form.email"
        class="w-full rounded border border-slate-600 bg-slate-950 p-4 text-slate-500 opacity-60 shadow-lg transition focus:opacity-100 focus:outline-none" />
    </div>

    <button
      :disabled="form.processing"
      type="submit"
      class="disabled:hover:none mt-12 w-full rounded border border-sky-700 bg-sky-950 p-4 text-sky-300 transition hover:bg-sky-700 hover:text-sky-200 disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:bg-sky-950">
      Réinitialiser mon mot de passe
    </button>
  </form>
</template>
