// inertia/pages/auth/register.tsx
import { Head, Link, useForm } from '@inertiajs/react'
import { Button, Field, Input, Label } from '@headlessui/react'
import Spinner from '~/components/spinner'
import clsx from 'clsx'

function Register() {
  const form = useForm({
    username: '',
    email: '',
    password: '',
  })

  function submit(e: React.FormEvent) {
    e.preventDefault()

    form.post('/register', {
      onError: () => {
        form.reset('password')
      },
    })
  }

  return (
    <>
      <Head>
        <title>Créer un compte</title>
      </Head>

      <div className="flex flex-col items-center">
        <h1 className="text-4xl font-medium text-slate-700">Créer un compte</h1>
        <span className="text-slate-500">
          ou{' '}
          <Link href="/login" className="text-amber-500 hover:underline">
            se connecter
          </Link>
        </span>
      </div>

      <form onSubmit={submit} className="flex w-full flex-col space-y-6">
        <Field className="space-y-1">
          <Label className="text-slate-700">Nom d'utilisateur</Label>
          <Input
            type="text"
            required
            value={form.data.username}
            onChange={(e) => form.setData('username', e.target.value)}
            className={clsx(
              'w-full rounded border border-slate-300 bg-slate-100 p-4 text-slate-500 transition data-[focus]:border-amber-300 data-[focus]:bg-amber-50 data-[focus]:outline-none',
              form.errors.username && 'border-red-300 !bg-red-50 data-[focus]:border-red-300'
            )}
          />
          {form.errors.username && (
            <span className="flex items-center gap-2 text-sm text-red-500">
              {form.errors.username}
            </span>
          )}
        </Field>

        <Field className="space-y-1">
          <Label className="text-slate-700">Adresse e-mail</Label>
          <Input
            type="email"
            required
            value={form.data.email}
            onChange={(e) => form.setData('email', e.target.value)}
            className={clsx(
              'w-full rounded border border-slate-300 bg-slate-100 p-4 text-slate-500 transition data-[focus]:border-amber-300 data-[focus]:bg-amber-50 data-[focus]:outline-none',
              form.errors.email && 'border-red-300 !bg-red-50 data-[focus]:border-red-300'
            )}
          />
          {form.errors.email && (
            <span className="flex items-center gap-2 text-sm text-red-500">
              {form.errors.email}
            </span>
          )}
        </Field>

        <Field className="space-y-1">
          <Label className="text-slate-700">Mot de passe</Label>
          <Input
            type="password"
            required
            value={form.data.password}
            onChange={(e) => form.setData('password', e.target.value)}
            className={clsx(
              'w-full rounded border border-slate-300 bg-slate-100 p-4 text-slate-500 transition data-[focus]:border-amber-300 data-[focus]:bg-amber-50 data-[focus]:outline-none',
              form.errors.password && 'border-red-300 !bg-red-50 data-[focus]:border-red-300'
            )}
          />
          {form.errors.password && (
            <span className="flex items-center gap-2 text-sm text-red-500">
              {form.errors.password}
            </span>
          )}
        </Field>

        <Button
          type="submit"
          disabled={form.processing}
          className="flex justify-center rounded border border-amber-600 bg-amber-500 p-4 text-white transition data-[disabled]:cursor-not-allowed data-[hover]:opacity-80"
        >
          {form.processing ? <Spinner text="Création" /> : 'Créer un compte'}
        </Button>
      </form>
    </>
  )
}

export default Register

// resources/js/pages/auth/Register.vue
<script setup>
import { useForm } from '@inertiajs/vue3'
import { ExclamationTriangleIcon } from '@heroicons/vue/20/solid'

const form = useForm({
  username: '',
  email: '',
  password: '',
})

function submit() {
  form.post('/register', {
    onError: () => {
      form.reset('password')
      document.activeElement.blur()
    },
    replace: true,
  })
}
</script>

<template>
  <Head title="Créer un compte" />

  <form @submit.prevent="submit" autocomplete="off" novalidate>
    <div class="mb-6">
      <label for="username" class="mb-3 flex items-center justify-between text-slate-300">
        <span class="font-medium">Nom d'utilisateur</span>

        <div v-if="form.errors.username" class="flex items-center gap-2 text-sm text-red-500">
          <ExclamationTriangleIcon class="h-5 w-5" />
          <span>{{ form.errors.username[0] }}</span>
        </div>
      </label>
      <input
        required
        type="text"
        id="username"
        name="username"
        v-model.trim="form.username"
        class="w-full rounded border border-slate-600 bg-slate-950 p-4 text-slate-500 opacity-60 shadow-lg transition focus:opacity-100 focus:outline-none" />
    </div>

    <div class="mb-6">
      <label for="email" class="mb-3 flex items-center justify-between text-slate-300">
        <span class="font-medium">Adresse e-mail</span>
        <div v-if="form.errors.email" class="flex items-center gap-2 text-sm text-red-500">
          <ExclamationTriangleIcon class="h-5 w-5" />
          <span>{{ form.errors.email[0] }}</span>
        </div>
      </label>
      <input
        required
        type="email"
        id="email"
        name="email"
        v-model.trim="form.email"
        class="w-full rounded border border-slate-600 bg-slate-950 p-4 text-slate-500 opacity-60 shadow-lg transition focus:opacity-100 focus:outline-none" />
    </div>

    <div class="mb-6">
      <label for="password" class="mb-3 flex items-center justify-between text-slate-300">
        <span class="font-medium">Mot de passe</span>
        <div v-if="form.errors.password" class="flex items-center gap-2 text-sm text-red-500">
          <ExclamationTriangleIcon class="h-5 w-5" />
          <span>{{ form.errors.password[0] }}</span>
        </div>
      </label>
      <input
        required
        type="password"
        id="password"
        name="password"
        v-model.trim="form.password"
        class="w-full rounded border border-slate-600 bg-slate-950 p-4 text-slate-500 opacity-60 shadow-lg transition focus:opacity-100 focus:outline-none" />
    </div>

    <button
      :disabled="form.processing"
      type="submit"
      class="disabled:hover:none mt-12 w-full rounded border border-sky-700 bg-sky-950 p-4 text-sky-300 transition hover:bg-sky-700 hover:text-sky-200 disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:bg-sky-950">
      Créer un compte
    </button>

    <div class="mt-12 flex justify-between">
      <Link href="/login" class="text-sm font-medium text-sky-500 transition hover:text-slate-300">
        J'ai déjà un compte
      </Link>
    </div>
  </form>
</template>
